<?php

use Carbon\CarbonImmutable;
use Fmeccanici\Dlvr\CreateWorkWeek;
use Fmeccanici\Dlvr\DayOfWeek;
use Fmeccanici\Dlvr\Time;
use Fmeccanici\Dlvr\WorkDay;
use Fmeccanici\Dlvr\WorkHours;
use Fmeccanici\Dlvr\WorkSchedule;
use PHPUnit\Framework\TestCase;

class WorkScheduleTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /** @test */
    public function it_should_set_a_regular_work_day()
    {
        // Given
        $companyId = uniqid();
        $dayOfWeek = DayOfWeek::MONDAY;
        $workWeek = CreateWorkWeek::regular()->removeWorkDay($dayOfWeek);
        $workSchedule = new WorkSchedule($workWeek);
        $regularWorkDay = new WorkDay($dayOfWeek, new WorkHours(new Time(9, 0, 0), new Time(17, 0, 0)));

        // When
        $workWeek = $workSchedule->workweek()->setWorkDay($regularWorkDay);

        // Then
        self::assertEquals($regularWorkDay, $workWeek->workDayAt($dayOfWeek));
    }
    
    /** @test */
    public function it_should_calculate_if_date_is_a_work_day()
    {
        $companyId = uniqid();
        $dayOfWeek = DayOfWeek::MONDAY;
        $workWeek = CreateWorkWeek::regular();
        $workSchedule = new WorkSchedule($workWeek);

        // When
        $dateAtMonday = CarbonImmutable::now()->next($dayOfWeek);
        $workDay = $workSchedule->workDay($dateAtMonday->year, $dateAtMonday->month, $dateAtMonday->day);

        // Then
        self::assertEquals($workDay, $workWeek->workDayAt($dayOfWeek));
    }

    /** @test */
    public function it_should_calculate_due_date()
    {
        // Given
        $dayOfWeek = DayOfWeek::MONDAY;
        $workWeek = CreateWorkWeek::regular();
        $workSchedule = new WorkSchedule($workWeek);
        $startDate = CarbonImmutable::now()->next($dayOfWeek)->setHour(16)->setMinute(0);

        // When
        $dueDate = $workSchedule->dueDate($startDate, 2);

        // Then
        self::assertEquals($startDate->addDays(2)->startOfDay(), $dueDate->startOfDay());
        self::assertEquals(9, $dueDate->hour);
        self::assertEquals(0, $dueDate->minute);
    }
    
    /** @test */
    public function it_should_start_next_day_if_after_work_hours()
    {
        // Given
        
        // When
        
        // Then
        
    }
    
    /** @test */
    public function it_should_start_same_day_if_before_work_hours()
    {
        // Given
        
        // When
        
        // Then
        
    }
    
    /** @test */
    public function it_should_take_into_account_irregular_work_day()
    {
        // Given
        
        // When
        
        // Then
        
    }
    
    /** @test */
    public function it_should_take_into_account_holidays()
    {
        // Given
        
        // When
        
        // Then
        
    }
}